name       : xboxdrv
version    : 0.8.8
release    : 1
source     :
    - http://github.com/xboxdrv/xboxdrv/archive/v0.8.8.tar.gz : 2d0ee8c8c1c0e5c2d84e0302766012c95f063a82c3a6207d6f0298c32ae6a24b
license    : GPL-3.0
summary    : Xbox/Xbox360 gamepad driver in userspace
component  : system.utils
description: |
    Xbox/Xbox360 gamepad driver for Linux that works in userspace.
builddeps  :
    - libboost-devel
    - pkgconfig(libusb-1.0)
    - pkgconfig(x11-xcb)
    - scons
setup      : |
    sed 's/\/local//' -i Makefile
build      : |
    %make
install    : |
    %make_install